# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text=b'Nombre Docente', max_length=255)),
                ('curso', models.CharField(help_text=b'Nombre Curso', max_length=255)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
